### ISSUE TITLE
I want to know whether current version can connect to backend and run successfully?

### ISSUE THREAD

**Issue by lbyzju** [openimsdk/openim-reactnative-demo#2]
### What happened?

我就想知道现在的版本是否能正常的连接后端并且可以运行?

### What did you expect to happen?

我就想知道现在的版本是否能正常的连接后端并且可以运行?

### How can we reproduce it (as minimally and precisely as possible)?

我就想知道现在的版本是否能正常的连接后端并且可以运行?

### Anything else we need to know?

我就想知道现在的版本是否能正常的连接后端并且可以运行?

### version

我就想知道现在的版本是否能正常的连接后端并且可以运行?

### Cloud provider

我就想知道现在的版本是否能正常的连接后端并且可以运行?

### OS version

我就想知道现在的版本是否能正常的连接后端并且可以运行?

### Install tools

我就想知道现在的版本是否能正常的连接后端并且可以运行?

**Comment by westzmg** [comment]
可以正常运行，只是调试过程能参考的内容太少了
