### ISSUE TITLE
[BUG] An error occurred running on ios

### ISSUE THREAD

**Issue by 15975019972** [openimsdk/openim-reactnative-demo#20]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

我这边直接使用npm run start之后就提示
![image](https://github.com/user-attachments/assets/c5ff8cbb-c912-46de-8396-9c39fbaea884)
react-native-cli: 2.0.1

### Screenshots Link

我这边直接使用npm run start之后就提示
![image](https://github.com/user-attachments/assets/c5ff8cbb-c912-46de-8396-9c39fbaea884)
react-native-cli: 2.0.1

**Comment by lgz5689** [comment]
run `npx react-native doctor` check

**Comment by 15975019972** [comment]
![image](https://github.com/user-attachments/assets/69bc90da-b1d5-46f8-8371-940f3edac84a)
目前使用的ios

**Comment by 15975019972** [comment]
可以了，需要在ios文件，pod install 才可以

**Comment by lgz5689** [comment]
> 可以了，需要在ios文件，pod install 才可以

Good
