### ISSUE TITLE
[BUG]error [AxiosError: Network Error]

### ISSUE THREAD

**Issue by 15975019972** [openimsdk/openim-reactnative-demo#22]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

 error [AxiosError: Network Error]
 LOG  [AxiosError: Network Error]
![image](https://github.com/user-attachments/assets/a98fa626-721a-40c5-9a71-107a6c1e3ae9)

**Comment by lgz5689** [comment]
Please check whether your service has been successfully deployed

**Comment by 15975019972** [comment]
> Please check whether your service has been successfully deployed

服务器配置没有问题，使用http://xxxxxx:11001/#/chat，能注册成功，但是使用rn app就提示我网络错误

**Comment by 15975019972** [comment]
![image](https://github.com/user-attachments/assets/32ef818d-73c2-4bf1-9696-12bce287b3e2)

**Comment by 15975019972** [comment]
![image](https://github.com/user-attachments/assets/0a73bf3f-766c-409b-8955-29e11943bbfd)
用postman 测试还是可以请求到了

**Comment by lgz5689** [comment]
You can try writing a request and sending it to baidu.com and other websites to see if there is a problem with the simulator network

**Comment by 15975019972** [comment]
你使用ip地址试试看，我怀疑是使用ip地址是会提示网络错误。是否是因为ip地址的问题，要替换域名形式
![image](https://github.com/user-attachments/assets/71431443-199f-44af-ada1-833aac3927ce)

**Comment by lgz5689** [comment]
Not sure about your server deployment and network Settings, it seems to be a problem on your side

**Comment by lgz5689** [comment]
You try to access the normal api with a data response, so I suspect a server side issue

**Comment by 15975019972** [comment]
我将我线上域名给你，因为是按照官网的形式部署的，我使用postman可以请求到数据，但是使用模拟器axios提示网络错误，我找不到原因。最直接我能找到是因为域名和ip地址的区别
