### ISSUE TITLE
[BUG] Messages cannot be received in real time

### ISSUE THREAD

**Issue by 15975019972** [openimsdk/openim-reactnative-demo#23]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

![image](https://github.com/user-attachments/assets/9a9eca0c-75b6-411c-aee3-67c5e0cc2fee)
通过web端发送消息，ios不能实时收到web端发送到消息。

以下是控制台输出的信息
![image](https://github.com/user-attachments/assets/907a4c52-8229-459d-b897-e58e0646c0ad)

**Comment by lgz5689** [comment]
I see that you sent four messages and one of them was read, is it possible that only the first of the four messages was received

**Comment by PolarisYan** [comment]
> I see that you sent four messages and one of them was read, is it possible that only the first of the four messages was received

@lgz5689 
Meet same problem on ios 17.5 simulator, test on commit: aa647a12defcce6469ac53468ada14663be02366
Can't see new message when current page is 'Chat'. But can see all message when re-entry 'Chat'.

And it work well on Android.

I write console.log in newMessageHandler, bug nothing print on console. Is it a sdk bug?

**Comment by lgz5689** [comment]
https://github.com/openimsdk/open-im-sdk-reactnative/pull/49
It has been fixed in this pr, please update to the latest version.
