### ISSUE TITLE
[BUG] android:build The APK compiled by Android cannot be logged in

### ISSUE THREAD

**Issue by weizihua** [openimsdk/openim-reactnative-demo#26]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

安卓编译出 正式包 无法进行登录 也无法进行注册

"android:clean:build": "cd ./android && ./gradlew clean && ./gradlew assembleRelease && cd ..",

**Comment by lgz5689** [comment]
Is it normal in development mode? Please provide detailed log, otherwise it can not help you solve.
