### ISSUE TITLE
The chat dialog page does not automatically display the latest messages

### ISSUE THREAD

**Issue by jingqiuJQ** [openimsdk/openim-reactnative-demo#4]
### What happened?

当好友发送消息时，聊天对话页面无法自动显示最新一条消息

### What did you expect to happen?

希望在Demo中解决该问题，更好的理解该项目

### How can we reproduce it (as minimally and precisely as possible)?

进入某一好友聊天页面，该好友发送新消息，当前聊天页面无法查看最新消息

### version

master 分支
commit id e8e4a31c4da2150cb59fa0a78a7533af09cfc592

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by AndrewZuo01** [comment]
already solved in new version
